# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('authtools.user',),
        ),
    ]
